version: "3.6"

services:
  
  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:7.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:80"
    network_mode: "host"